# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prototype_type', models.IntegerField(choices=[(0, 'Single Unit'), (1, 'Multiple Units')], default=0)),
                ('need_assistance', models.IntegerField(choices=[(0, 'No, I have my own 3D CAD model ready to upload.'), (1, 'Yes, I need help designing a 3D model.')], default=0)),
                ('basic_material', models.IntegerField(choices=[(0, 'Plastic / Resin'), (1, 'Metal'), (2, 'Stone'), (3, 'Other')], default=0)),
                ('material', models.IntegerField(blank=True, choices=[(0, 'PLA (Polylactide)'), (1, 'ABS (Acrylonitrile Butadiene Styrene)'), (2, 'ABS-Like'), (3, 'PETG (Polyethylene Terephthalate)'), (4, 'TPE (Thermoplastic Elastomers)'), (5, 'PC (Polycarbonate)'), (6, 'Nylon'), (7, 'Reinforced Nylon'), (8, 'Sandstone'), (9, 'Stainless Steel'), (10, 'Titanium'), (11, 'Aluminum')], null=True)),
                ('process', models.IntegerField(blank=True, choices=[(0, 'Fused Deposition Modeling (FDM)'), (1, 'Stereoligtography (SLM)'), (2, 'Selective Laser Sintering (SLS)'), (3, 'Material Jetting (MJ)'), (4, 'Binder Jetting (BJ) (Stone)'), (5, 'Electron Beam Melting (EBM) (Metals)')], null=True)),
                ('is_flexible', models.BooleanField(default=True)),
                ('is_semi_biodegradable', models.BooleanField(default=True)),
                ('is_heat_withstand', models.BooleanField(default=True)),
                ('size', models.IntegerField(choices=[(0, 'I am not sure'), (1, 'Small (Cubic Millimeters)'), (2, 'Medium (Cubic Centimeters)'), (3, 'Large (Cubic Meters)')], default=0)),
                ('consideration', models.IntegerField(choices=[(0, 'Speed'), (1, 'Accuracy'), (2, 'Cost')], default=0)),
                ('budget', models.IntegerField(choices=[(0, 'Under $100'), (1, '$100 - 500'), (2, '$500 - 2,500'), (3, '$2,500+')], default=0)),
                ('geo_matters', models.IntegerField(choices=[(0, 'No, I do not care about location.'), (1, 'Yes, I want to be close to my provider.')], default=0)),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas)'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=3, null=True)),
                ('description', models.TextField()),
                ('cad_file', models.FileField(blank=True, null=True, upload_to='cads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
