# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20170906_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='heat_resistance',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'I want my project to be able to withstand heat.'), (2, 'My project requires neither heat resistance or flexibility'), (3, 'I want my project to be flexible')], default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_able_to_bend',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_better_appearance',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_extreme_strength',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_food_safe_plastic',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_full_color',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_functional_metal',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_functional_or_basic',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Functional'), (2, 'As Basic as possible')], default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_highest_detail',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_precious_metal',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='metal_concern',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Conductivity'), (2, 'Strength')], default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='metal_decision',
            field=models.IntegerField(choices=[(0, 'None'), (2, 'I want the very best for top dollar. ($250+ per print)'), (2, 'No, but I still want a high quality metal')], default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='other_materials',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'I want my project to be wood-like'), (2, 'I want my project to be made from stone')], default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='plastic_concern',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Cost'), (2, 'Quality')], default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='plastic_decision',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Yes, I am willing to pay slightly more to get a better material'), (2, 'No I want my project to pretty simple for a pretty low price')], default=0),
        ),
    ]
