# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20170906_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='metal_decision',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'I want the very best for top dollar. ($250+ per print)'), (2, 'No, but I still want a high quality metal')], default=0),
        ),
    ]
