# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20170907_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_functional_metal',
        ),
    ]
