# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20170908_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.IntegerField(choices=[(0, 'Less than $100'), (1, '$100 - 250'), (2, '$250 - 500'), (2, '500 - 2,500'), (3, '$2,500 plus')], default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_time_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping',
            field=models.IntegerField(choices=[(0, 'No, timing is not an issue for me.'), (1, 'Yes, I need this project manufactured as soon as physically possible.')], default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='basic_material',
            field=models.IntegerField(choices=[(0, 'Individual'), (1, 'A Small Business'), (2, 'Industrial Business')], default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='budget',
            field=models.IntegerField(choices=[(0, 'Less than $100'), (1, '$100 - 250'), (2, '$250 - 500'), (2, '500 - 2,500'), (3, '$2,500 plus')], default=0),
        ),
    ]
