# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20170911_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='basic_material',
            field=models.IntegerField(choices=[(0, 'Plastic / Resin'), (1, 'Metal'), (2, 'Stone'), (3, 'Other')], default=0),
        ),
    ]
