# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20170913_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_able_to_bend',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'I want my project to handle some bending, but not to be rubber like'), (3, 'I want my project to feel and act almost like rubber')], default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_better_appearance',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'I want a more functional material for my project'), (3, 'I want a better looking appearance for my project')], default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_extreme_strength',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'I am willing to spend top dollar ($250+) for the very best quality available'), (3, "No I don't need extreme strength and performance")], default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_food_safe_plastic',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'I want my project to be generally safe around food'), (3, "No, I don't need my project to be foodsafe")], default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_full_color',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Yes, I want rich and full colors for my project'), (3, "No I don't need my project to have full colors, just printed in high detail")], default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_highest_detail',
            field=models.IntegerField(choices=[(0, 'Unknown'), (2, 'Yes, I want the highest detail possible'), (3, "I want detail, but don't need the highest detail possible")], default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_precious_metal',
            field=models.IntegerField(choices=[(0, 'None'), (2, 'I want my project to be constructed from precious metals. ($250+ per print)'), (3, 'I want my project constructed by more functional metals')], default=0),
        ),
    ]
