# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20170913_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='material',
            field=models.IntegerField(blank=True, choices=[(0, 'PLA (Polylactide)'), (1, 'ABS (Acrylonitrile Butadiene Styrene)'), (2, 'ABS-Like'), (3, 'PETG (Polyethylene Terephthalate)'), (4, 'TPE (Thermoplastic Elastomers)'), (5, 'PC (Polycarbonate)'), (6, 'Nylon'), (7, 'Reinforced Nylon'), (8, 'Sandstone'), (9, 'Stainless Steel'), (10, 'Titanium'), (11, 'Aluminum'), (12, 'Silver / Gold'), (13, 'Copper'), (14, 'Inconel'), (15, 'Wood-Like'), (16, 'PEEK'), (17, 'PEI'), (18, 'Alumide'), (19, 'Resins')], null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='process',
            field=models.IntegerField(blank=True, choices=[(0, 'Fused Deposition Modeling (FDM)'), (1, 'Stereoligtography (SLM)'), (2, 'Selective Laser Sintering (SLS)'), (3, 'Material Jetting (MJ)'), (4, 'Binder Jetting (BJ) (Stone)'), (5, 'Electron Beam Melting (EBM) (Metals)'), (6, 'SLA'), (7, 'PolyJet'), (8, 'Various')], null=True),
        ),
    ]
