# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20170929_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='need_assistance',
            field=models.IntegerField(choices=[(0, 'No, I have my own 3D CAD model ready to upload.'), (1, 'Yes, I need help designing a 3D model.')], default=1),
        ),
    ]
