# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-06 09:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_customer_performance_or_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cad_file',
            field=models.FileField(blank=True, null=True, upload_to='cads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'obj', 'step', 'iges'])]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='process',
            field=models.IntegerField(blank=True, choices=[(0, 'Fused Deposition Modeling (FDM)'), (1, 'Selective Laser Melting / Direct Metal Laser Sintering (SLM / DMLS)'), (2, 'Selective Laser Sintering (SLS)'), (4, 'Binder Jetting (BJ) (Stone)'), (5, 'Electron Beam Melting (EBM) (Metals)'), (6, 'Stereolithography (SLA)'), (7, 'PolyJet / Material Jetting (MJ)'), (8, 'Various')], null=True),
        ),
    ]
