# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-23 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20181006_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_expedited',
            field=models.IntegerField(choices=[(0, 'No, time is not an issue in manufacturing my project'), (1, 'Yes I require the project to be manufactured as fast as possible.')], default=1),
        ),
    ]
