# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-21 13:31
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_customer_is_expedited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='shipping',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'International Shipping'), (1, 'Expedited Shipping (2-3 days roughly from completion)'), (2, 'Next Day Shipping')], max_length=5, null=True),
        ),
    ]
