# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 10:09
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Leave blank if you want coupon number to be generated automatically', max_length=6, null=True, unique=True)),
                ('duration', models.IntegerField(blank=True, help_text='Coupon duration in days. Leave blank if its a one-time deal', null=True)),
                ('discount', models.PositiveIntegerField(help_text='Discount value in percents, for e.g. 10 or 50', validators=[django.core.validators.MaxValueValidator(100)])),
                ('expired', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
