# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.IntegerField(choices=[(0, 'Comment'), (1, 'Suggestion'), (2, 'Question'), (3, 'General Inquiry'), (4, 'Business Inquiry')], default=0)),
                ('body', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('from_email', models.EmailField(default='no-reply@findyour3d.com', max_length=254)),
                ('reply_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
