# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Company')], default=1),
        ),
    ]
