# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171003_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_trial',
        ),
    ]
