# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.IntegerField(blank=True, choices=[(1, 'Starter'), (2, 'Premium - 3 month'), (3, 'Premium - 12 month')], null=True),
        ),
    ]
