# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 05:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('ideal_customer', models.IntegerField(choices=[(0, 'Individuals'), (1, 'Small Businesses'), (2, 'Large/Industrial Businesses')], default=0)),
                ('is_cad_assistance', models.BooleanField(default=False)),
                ('budget', models.IntegerField(choices=[(0, 'Under $100'), (1, '$100 - 500'), (2, '$500 - 2,500'), (3, '$2,500+')], default=0)),
                ('basic_material', models.IntegerField(choices=[(0, 'Plastic / Resin'), (1, 'Metal'), (2, 'Stone'), (3, 'Other')], default=0)),
                ('consideration', models.IntegerField(choices=[(0, 'Speed'), (1, 'Accuracy'), (2, 'Cost')], default=0)),
                ('printing_options', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'FDM (Fused Deposition Modeling)'), (1, 'SLA (Sterolithography)'), (2, 'DLP (Digital Light Processing)'), (3, 'SLS (Selective Laser Sintering)'), (4, 'Material Jetting (PolyJet / MultiJet)'), (5, 'BJ (Binderjetting)'), (6, 'EBM (Electron Beam Melting)')], max_length=13)),
                ('material', models.IntegerField(blank=True, choices=[(0, 'PLA (Polylactide)'), (1, 'ABS (Acrylonitrile Butadiene Styrene)'), (2, 'ABS-Like'), (3, 'PETG (Polyethylene Terephthalate)'), (4, 'TPE (Thermoplastic Elastomers)'), (5, 'PC (Polycarbonate)'), (6, 'Nylon'), (7, 'Reinforced Nylon'), (8, 'Sandstone'), (9, 'Stainless Steel'), (10, 'Titanium'), (11, 'Aluminum')], null=True)),
                ('top_printing_processes', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'FDM (Fused Deposition Modeling)'), (1, 'SLA (Sterolithography)'), (2, 'DLP (Digital Light Processing)'), (3, 'SLS (Selective Laser Sintering)'), (4, 'Material Jetting (PolyJet / MultiJet)'), (5, 'BJ (Binderjetting)'), (6, 'EBM (Electron Beam Melting)')], max_length=13)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
