# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 07:23
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20170921_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='top_printing_processes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Fused Deposition Modeling (FDM)'), (1, 'Stereoligtography (SLM)'), (2, 'Selective Laser Sintering (SLS)'), (3, 'Material Jetting (MJ)'), (4, 'Binder Jetting (BJ) (Stone)'), (5, 'Electron Beam Melting (EBM) (Metals)'), (6, 'SLA'), (7, 'PolyJet'), (8, 'Various')], max_length=17),
        ),
    ]
