# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 07:45
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations

company_list = [
    {
        '1': {
            'name': 'TPE Company',
            'address_line_1': 'Washington, DC 20521-2050',
            'address_line_2': '2050 Bamako Place',
            'full_name': 'Charles W. Anderson',
            'email': 'pla_1@email.com',
            'phone': '+1(234) 5678 72',
            'website': 'pla_1.com',
            'is_cad_assistance': True,
            'ideal_customer': 0,
            'budget': 1,
            'material': 4,
            'top_printing_processes': ['0', '5'],
            'description': 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?'
        },

        '2': {
            'name': 'Nylon Company',
            'address_line_1': 'Washington, DC 20521-7100',
            'address_line_2': '7100 Athens Place',
            'full_name': 'Kathleen S. Holden',
            'email': 'abs@email.com',
            'phone': '+1(234) 5678 72',
            'website': 'abs_1.com',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 2,
            'material': 6,
            'top_printing_processes': ['2', '1'],
            'description': 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat'
        },

        '3': {
            'name': 'Resins Company',
            'address_line_1': 'Washington, DC 20521-7100',
            'address_line_2': '8400 London Place',
            'full_name': 'Denise W. Williams',
            'email': 'petg@email.com',
            'phone': '+1(234) 5678 72',
            'website': 'petg.com',
            'is_cad_assistance': False,
            'ideal_customer': 2,
            'budget': 2,
            'material': 19,
            'top_printing_processes': ['6', '2'],
            'description': 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains'
        },
        '4': {
            'name': 'Reinforced Nylon LLC',
            'address_line_1': 'Washington, DC 20521-7100',
            'address_line_2': '5520 Quebec Place',
            'full_name': 'Douglas E. Carter',
            'email': 'nylon@email.com',
            'phone': '+1(234) 5678 72',
            'website': '',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 3,
            'material': 7,
            'top_printing_processes': ['0', '4'],
            'description': 'n a professional context it often happens that private or corporate clients corder a publication to be made and presented with the actual content still not being ready. Think of a news blog thats filled with content hourly on the day of going live. However, reviewers tend to be distracted by comprehensible content, say, a random text copied from a newspaper or the internet. The are likely to focus on the text, disregarding the layout and its elements. Besides, random text risks to be unintendedly humorous or offensive, an unacceptable risk in corporate environments. Lorem ipsum and its many variants have been employed since the early 1960ies, and quite likely since the sixteenth century.'
        },
        '5': {
            'name': 'Alumide CORP',
            'address_line_1': 'Washington, DC 20521-7100',
            'address_line_2': '6170 Peshwar Place',
            'full_name': 'William J. Bryant',
            'email': 'William@email.com',
            'phone': '+1(234) 5678 72',
            'website': '',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 4,
            'material': 18,
            'top_printing_processes': ['0', '3'],
            'description': 'Most of its text is made up from sections 1.10.32–3 of Ciceros De finibus bonorum et malorum (On the Boundaries of Goods and Evils; finibus may also be translated as purposes). Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit is the first known version ("Neither is there anyone who loves grief itself since it is grief and thus wants to obtain it"). It was found by Richard McClintock, a philologist, director of publications at Hampden-Sydney College in Virginia; he searched for citings of consectetur in classical Latin literature, a term of remarkably low frequency in that literary corpus.'
        },
        '6': {
            'name': 'Sandstone TEAM',
            'address_line_1': 'Washington, DC 20521-7100',
            'address_line_2': '',
            'full_name': 'Charles B. Evans',
            'email': 'Charlesvans@email.com',
            'phone': '+1(234) 5678 72',
            'website': '',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 0,
            'material': 8,
            'top_printing_processes': ['7', '0'],
            'description': 'Cicero famously orated against his political opponent Lucius Sergius Catilina. Occasionally the first Oration against Catiline is taken for type specimens: Quo usque tandem abutere, Catilina, patientia nostra? Quam diu etiam furor iste tuus nos eludet? (How long, O Catiline, will you abuse our patience? And for how long will that madness of yours mock us?)'
        },
        7: {
            'name': 'PEEK Company',
            'address_line_1': 'Washington, DC 20521-4150',
            'address_line_2': '4150 Sydney Place',
            'full_name': 'Cynthia Ervin',
            'email': '@email.com',
            'phone': '+1(234) 5678 72',
            'website': '',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 1,
            'material': 16,
            'top_printing_processes': ['8', ],
            'description': 'Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam '
        },
        8: {
            'name': 'PETG Castle LLC',
            'address_line_1': 'Washington, DC 20521-4150',
            'address_line_2': '4150 Sydney Place',
            'full_name': 'Janet K. Barlow',
            'email': 'JanetBarlow@email.com',
            'phone': '+1(234) 5678 72',
            'website': '',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 2,
            'material': 3,
            'top_printing_processes': ['1', '0', '2'],
            'description': 'est, qui dolorem ipsum, quia dolor sit amet, consectetur, adipisci[ng] velit, sed quia non numquam [do] eius modi tempora inci[di]dunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur?'
        },
        9: {
            'name': 'Nylon Company',
            'address_line_1': 'Washington, DC 20521-4150',
            'address_line_2': '4150 Sydney Place',
            'full_name': 'Harry W. Jones',
            'email': 'harry@email.com',
            'phone': '+1(234) 5678 72',
            'website': '',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 3,
            'material': 6,
            'top_printing_processes': ['0', ],
            'description': 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are '
        },
        10: {
            'name': 'PLA Company',
            'address_line_1': 'Washington, DC 20521-4150',
            'address_line_2': '4150 Sydney Place',
            'full_name': 'Cynthia Ervin',
            'email': 'CynthiaErvin@email.com',
            'phone': '+1(234) 5678 72',
            'website': '',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 4,
            'material': 0,
            'top_printing_processes': ['0', ],
            'description': 'extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?'
        },
        11: {
            'name': 'PETG LLC',
            'address_line_1': 'Washington, DC 20521-4150',
            'address_line_2': '4150 Sydney Place',
            'full_name': 'Evan Charles',
            'email': 'evan@email.com',
            'phone': '+1(234) 5678 72',
            'website': '',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 1,
            'material': 3,
            'top_printing_processes': ['0', ],
            'description': 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.'
        },
        12: {
            'name': 'Sandstone COMPANY',
            'address_line_1': 'Washington, DC 20521-4150',
            'address_line_2': '4150 Sydney Place',
            'full_name': 'Charles B. Evans',
            'email': 'charles@email.com',
            'phone': '+1(234) 5678 72',
            'website': '',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 2,
            'material': 8,
            'top_printing_processes': ['4', ],
            'description': 'In 1985 Aldus Corporation launched its first desktop publishing program Aldus PageMaker for Apple Macintosh computers, released in 1987 for PCs running Windows 1.0. Both contained the variant lorem ipsum most common today. Laura Perry, then art director with Aldus, modified prior versions of Lorem Ipsum text from typographical specimens; in the 1960s and 1970s it appeared often in lettering catalogs by Letraset. Anecdotal evidence has it that Letraset used Lorem ipsum already from 1970 onwards, eg. for grids (page layouts) for ad agencies. Many early desktop publishing programs, eg. Adobe PageMaker, used it to create template.'
        },
        13: {
            'name': 'Wood-Like Company',
            'address_line_1': 'Washington, DC 20521-3290',
            'address_line_2': '4150 Sydney Place',
            'full_name': 'William',
            'email': 'William@email.com',
            'phone': '+1(234) 5678 72',
            'website': '',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 3,
            'material': 15,
            'top_printing_processes': ['1', '0'],
            'description': 'Most text editors like MS Word or Lotus Notes generate random lorem text when needed, either as pre-installed module or plug-in to be added. Word selection or sequence dont necessarily match the original, which is intended to add variety. Presentation software like Keynote or Pages use it as a samples for screenplay layout. Content management software as Joomla, Drupal, Mambo, PHP-Nuke, WordPress, or Movable Type offer Lorem Ipsum plug-ins with the same functionality.'
        },
        14: {
            'name': 'Stainless Steel COMPANY',
            'address_line_1': 'Washington, DC 20521-3290',
            'address_line_2': '4150 Sydney Place',
            'full_name': 'Bran Big',
            'email': 'big@email.com',
            'phone': '+1(234) 5678 72',
            'website': '',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 4,
            'material': 9,
            'top_printing_processes': ['1', ],
            'description': 'Do you like Cheese Whiz? Spray tan? Fake eyelashes? Thats what is Lorem Ipsum to many—it rubs them the wrong way, all the way. Its unreal, uncanny, makes you wonder if something is wrong, it seems to seek your attention for all the wrong reasons. Usually, we prefer the real thing, wine without sulfur based preservatives, real butter, not margarine, and so wed like our layouts and designs to be filled with real words, with thoughts that count, information that has value.'
        },

        15: {
            'name': 'Inconel LLC',
            'address_line_1': 'Washington, DC 20521-3290',
            'address_line_2': '4150 Sydney Place',
            'full_name': 'John Snow',
            'email': 'jon@email.com',
            'phone': '+1(234) 5678 72',
            'website': '',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 0,
            'material': 14,
            'top_printing_processes': ['1', ],
            'description': 'The toppings you may chose for that TV dinner pizza slice when you forgot to shop for foods, the paint you may slap on your face to impress the new boss is your business. But what about your daily bread? Design comps, layouts, wireframes—will your clients accept that you go about things the facile way? Authorities in our business will tell in no uncertain terms that Lorem Ipsum is that huge, huge no no to forswear forever. Not so fast, Id say, there are some redeeming factors in favor of greeking text, as its use is merely the symptom of a worse problem to take into consideration.'
        },
        16: {
            'name': 'Copper Com',
            'address_line_1': 'Washington, DC 20521-3290',
            'address_line_2': '4150 Sydney Place',
            'full_name': 'Nick Back',
            'email': 'nick@email.com',
            'phone': '+1(234) 5678 72',
            'website': '',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 0,
            'material': 13,
            'top_printing_processes': ['1', ],
            'description': 'You begin with a text, you sculpt information, you chisel away whats not needed, you come to the point, make things clear, add value, youre a content person, you like words. Design is no afterthought, far from it, but it comes in a deserved second. Anyway, you still use Lorem Ipsum and rightly so, as it will always have a place in the web workers toolbox, as things happen, not always the way you like it, not always in the preferred order. Even if your less into design and more into content strategy you may find some redeeming value with, wait for it, dummy copy, no less.'
        },
        17: {
            'name': 'Silver / Gold Company',
            'address_line_1': 'Washington, DC 20521-3290',
            'address_line_2': '4150 Sydney Place',
            'full_name': 'Jogn Smith',
            'email': 'joe@email.com',
            'phone': '+1(234) 5678 72',
            'website': '',
            'is_cad_assistance': True,
            'ideal_customer': 1,
            'budget': 0,
            'material': 12,
            'top_printing_processes': ['1', ],
            'description': 'But. A big but: Lorem Ipsum is not t the root of the problem, it just shows whats going wrong. Chances are there wasnt collaboration, communication, and checkpoints, there wasnt a process agreed upon or specified with the granularity required. Its content strategy gone awry right from the start. Forswearing the use of Lorem Ipsum wouldnt have helped, wont help now. Its like saying youre a bad designer, use less bold text, dont use italics in every other paragraph. True enough, but thats not all that it takes to get things back on track.'
        },
    }
]


def fill_init_companies(apps, schema_editor):
    company = apps.get_model('company', 'Company')
    user_obj = apps.get_model('users', 'User')
    try:
        user = user_obj.objects.get(id=2)
        if company.objects.count() == 0:
            for c in company_list:
                for k, v in c.items():
                    company.objects.create(
                        name=v['name'],
                        display_name=v['name'],
                        address_line_1=v['address_line_1'],
                        address_line_2=v['address_line_2'],
                        full_name=v['full_name'],
                        email=v['email'],
                        phone=v['phone'],
                        ideal_customer=v['ideal_customer'],
                        is_cad_assistance=v['is_cad_assistance'],
                        budget=v['budget'],
                        material=v['material'],
                        top_printing_processes=v['top_printing_processes'],
                        description=v['description'],
                        user=user,
                    )
    except ObjectDoesNotExist:
        pass


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('company', '0007_auto_20170921_0723'),
    ]

    operations = [
        migrations.RunPython(fill_init_companies),
    ]
