# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 08:22
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20171121_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='shipping',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'International Shipping'), (1, 'Expedited Shipping (2-3 Days)'), (2, 'Next Day Shipping')], max_length=5, null=True),
        ),
    ]
