# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 08:44
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20180221_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='budget',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Less than $100'), (1, '$100 - 250'), (2, '$250 - 500'), (3, '$500 - 2,500'), (4, '$2,500 plus')], default=0, max_length=9),
        ),
        migrations.AlterField(
            model_name='company',
            name='ideal_customer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Individuals'), (1, 'Small Businesses'), (2, 'Large/Industrial Businesses')], default=0, max_length=5),
        ),
    ]
