# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-10 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20180301_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='quote_limit',
            field=models.IntegerField(default=10),
        ),
    ]
