# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_company_quote_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
