# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-09 14:36
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20181109_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='printing_options',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'FDM (Fused Deposition Modeling)'), (1, 'SLA (Sterolithography)'), (2, 'DLP (Digital Light Processing)'), (3, 'SLS (Selective Laser Sintering)'), (4, 'Material Jetting (PolyJet / MultiJet)'), (5, 'BJ (Binderjetting)'), (6, 'EBM (Electron Beam Melting)')], max_length=13, null=True),
        ),
    ]
